[package]
name = "re_entity"
version = "0.1.0"
edition = "2021"


[lib]
path = "lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inventory.workspace = true