[package]
name = "tools"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tools"
path = "main.rs"
doc = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
